version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - /ouchistack-data/ssd/lnd-data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=lnd
      - POSTGRES_PASSWORD=lnd
      - POSTGRES_DB=lnd
      - POSTGRES_INITDB_ARGS=--locale=en_US.utf8
    networks:
      int-db:
    deploy:
      replicas: 1
  tor:
    image: ghcr.io/yuki-js/lnd-stack/tor:latest
    configs:
      - source: tor
        target: /etc/tor/torrc
        mode: 0444
    networks:
      int-tor-proxy:
      ext-tor:
    deploy:
      replicas: 1
  lnd:
    image: ghcr.io/yuki-js/lnd-stack/lnd:latest
    volumes:
      - /ouchistack-data/ssd/lnd-data:/data
      - /ouchistack-data/ssd/lnd-data/rpc:/rpc
    networks:
      int-db:
      ext-lnd:
      int-tor-proxy:
    ports:
      - 52032:9735
    environment:
      NETWORK: mainnet
    configs:
      - source: lnd
        target: /lnd.conf
        mode: 0444
    depends_on:
      - postgres
      - tor
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
  admin:
    image: ghcr.io/yuki-js/manchan/admin:latest
    volumes:
      - /ouchistack-data/ssd/lnd-data/rpc:/rpc
    networks:
      int-db:
      ext-admin:
    configs:
      - source: admin
        target: /app/admin/.env
        mode: 0444
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      APP_ENV: production
    depends_on:
      - lnd
    user: root:root

networks:
  int-tor-proxy:
    internal: true
  ext-tor:
    internal: false
  int-db:
    internal: true
  ext-lnd:
    internal: false
  ext-admin:
    internal: false

configs:
  lnd:
    file: ../configs/lnd.conf
  tor:
    file: ../configs/torrc
  admin:
    file: ../configs/admin.env