version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - /ouchistack-data/ssd/lnd-data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=lnd
      - POSTGRES_PASSWORD=lnd
      - POSTGRES_DB=lnd
      - POSTGRES_INITDB_ARGS=--locale=en_US.utf8
  lnd:
    image: ghcr.io/yuki-js/lnd-stack/lnd:latest
    volumes:
      - /ouchistack-data/ssd/lnd-data:/data
      - /ouchistack-data/ssd/lnd-data/rpc:/rpc
    networks:
      ext-lnd:
        aliases:
          - lnd2
      over-stack:
        aliases:
          - lnd2
    environment:
      NETWORK: mainnet
    configs:
      - source: lnd
        target: /lnd.conf
        mode: 0444
    deploy:
      placement:
        max_replicas_per_node: 1

networks:
  ext-lnd:
    internal: false
  over-stack:
    external: true
    name: over-stack

configs:
  lnd:
    file: ../configs/lnd.conf